name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "fc2fcab3-356b-4701-9640-f632d34c13e6"      # 替换为你创建的数据库 ID
